/**
 * 
 */
package in.wtc.hcis.bo.constants;

/**
 * @author Rohit
 *
 */
public interface ApplicationErrors {
	public final static String PATIENT_DOES_NOT_EXIST = "PATIENT_DOES_NOT_EXIST";
	public final static String PATIENT_CANNNOT_BE_DELETED = "PATIENT CANNOT BE DELETED";
	public final static String PATIENT_DETAILS_DOES_NOT_EXIST = "PATIENT_DETAILS_DOES_NOT_EXIST";
	public final static String PATIENT_DETAILS_HAVE_BEEN_MODIFIED = "PATIENT_DETAILS_HAVE_BEEN_MODIFIED";
	public final static String PATIENT_CONTACT_DETAILS_DOES_NOT_EXIST = "PATIENT_CONTACT_DETAILS_DOES_NOT_EXIST";
	public final static String PATIENT_DETAILS_COULD_NOT_BE_ADDED = "PATIENT_DETAILS_COULD_NOT_BE_ADDED";
	public final static String PATIENT_CONTACT_DETAILS_COULD_NOT_BE_ADDED = "PATIENT_CONTACT_DETAILS_COULD_NOT_BE_ADDED";
	public final static String PATIENT_DETAILS_COULD_NOT_BE_REMOVED = "PATIENT_DETAILS_COULD_NOT_BE_REMOVED";
	public final static String PATIENT_APPOINTMENT_COULD_NOT_BE_BOOKED = "PATIENT_APPOINTMENT_COULD_NOT_BE_BOOKED";
	public final static String PATIENT_DETAILS_COULD_NOT_BE_FETCHED = "PATIENT_DETAILS_COULD_NOT_BE_FETCHED";
	public final static String PATIENT_ALLERGIES_COULD_NOT_BE_FETCHED = "PATIENT_ALLERGIES_COULD_NOT_BE_FETCHED";
	public final static String PATIENT_ALLERGIES_COULD_NOT_BE_ADDED = "PATIENT_ALLERGIES_COULD_NOT_BE_ADDED";
	public final static String PATIENT_IMMUNIZATIONS_COULD_NOT_BE_FETCHED = "PATIENT_IMMUNIZATIONS_COULD_NOT_BE_FETCHED";
	public final static String PATIENT_IMMUNIZATIONS_COULD_NOT_BE_ADDED = "PATIENT_IMMUNIZATIONS_COULD_NOT_BE_ADDED";
	public final static String PATIENT_REFERRAL_COULD_NOT_BE_ADDED = "PATIENT_REFERRAL_COULD_NOT_BE_ADDED";
	public final static String REFFRAL_CODE_NOT_FOUND = "REFFRAL_CODE_NOT_FOUND";
	
	
	
	
	public final static String DOCTOR_ADD_FAILED = "DOCTOR_ADD_FAILED";
	public final static String DOCTOR_FIND_FAILED = "DOCTOR_FIND_FAILED";
	public final static String DOCTOR_GET_ADDRESS_FAILED = "DOCTOR_GET_ADDRESS_FAILED";
	public final static String DOCTOR_GET_DETAIL_FAILED = "DOCTOR_GET_DETAIL_FAILED";
	public final static String DOCTOR_MODIFY_FAILED = "DOCTOR_MODIFY_FAILED";
	public final static String DOCTOR_REMOVE_FAILED = "DOCTOR_REMOVE_FAILED";
	public final static String DOCTOR_GET_CONSULTATION_CHARGES = "DOCTOR_GET_CONSULTATION_CHARGES";
	
	String SERVICE_ADD_FAILED = "SERVICE_ADD_FAILED";
	String SERVICE_ASSIGNMENT_FAILED = "SERVICE_ASSIGNMENT_FAILED";
	String SERVICE_GROUP_ADD_FAILED = "SERVICE_GROUP_ADD_FAILED";
	String SERVICE_READ_FAILED = "SERVICE_READ_FAILED";
	String SERVICE_GROUP_READ_FAILED = "SERVICE_GROUP_READ_FAILED";
	String SERVICE_GROUP_NOT_FOUND = "SERVICE_GROUP_NOT_FOUND";
	String SERVICE_REMOVE_FAILED = "SERVICE_REMOVE_FAILED";
	String SERVICE_GROUP_REMOVE_FAILED = "SERVICE_GROUP_REMOVE_FAILED";
	String SERVICE_MODIFY_FAILED = "SERVICE_MODIFY_FAILED";
	String SERVICE_GROUP_MODIFY_FAILED = "SERVICE_GROUP_MODIFY_FAILED";
	String SERVICE_STATUS_NOT_FOUND = "SERVICE_STATUS_NOT_FOUND";
	String SERVICE_ORDER_REMOVE_FAILED = "SERVICE_ORDER_REMOVE_FAILED";
	String SERVICE_ORDER_CREATION_FAILED = "SERVICE_ORDER_CREATION_FAILED";
	String SERVICE_ORDER_READ_FAILED = "SERVICE_ORDER_READ_FAILED";
	String SERVICE_ORDER_UPDATE_FAILED = "SERVICE_ORDER_UPDATE_FAILED";
	String SERVICE_PACKAGE_STATUS_READ_FAILED = "SERVICE_PACKAGE_STATUS_READ_FAILED";
	String SERVICE_PACKAGE_CREATION_FAILED = "SERVICE_PACKAGE_CREATION_FAILED";
	String SERVICE_PACKAGE_ASSIGNMENT_FAILED = "SERVICE_PACKAGE_ASSIGNMENT_FAILED";
	String SERVICE_PACKAGE_READ_FAILED = "SERVICE_PACKAGE_READ_FAILED";
	String SERVICE_PACKAGE_REMOVE_FAILED = "SERVICE_PACKAGE_REMOVE_FAILED";
	String SERVICE_PACKAGE_UPDATE_FAILED = "SERVICE_PACKAGE_UPDATE_FAILED";
	String ASSIGNED_SERVICE_REMOVE_FAILED = "ASSIGNED_SERVICE_REMOVE_FAILED";
	String ASSIGNED_SERVICE_READ_FAILED = "ASSIGNED_SERVICE_READ_FAILED";
	String ASSIGNED_SERVICE_UPDATE_FAILED = "ASSIGNED_SERVICE_UPDATE_FAILED";
	String ASSIGNED_SERVICE_CANCEL_FAILED ="ASSIGNED_SERVICE_CANCEL_FAILED";
	String ASSIGNED_SERVICE_STATUS_READ_FAILED = "ASSIGNED_SERVICE_STATUS_READ_FAILED";
	String ASSIGNED_PACKAGE_REMOVE_FAILED = "ASSIGNED_PACKAGE_REMOVE_FAILED";
	String ASSIGNED_PACKAGE_READ_FAILED = "ASSIGNED_PACKAGE_READ_FAILED";
	String ASSIGNED_PACKAGE_CANCEL_FAILED = "ASSIGNED_PACKAGE_CANCEL_FAILED";
	
	String ASSIGNED_PACKAGE_STATUS_READ_FAILED = "ASSIGNED_PACKAGE_STATUS_READ_FAILED";
	String ASSIGNED_PACKAGE_UPDATE_FAILED = "ASSIGNED_PACKAGE_UPDATE_FAILED";
	String SERVICE_BILLING_FAILED = "SERVICE_BILLING_FAILED";
	String SERVICE_BILL_READ_FAILED = "SERVICE_BILL_READ_FAILED";
	String INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION";
	
	String PRESCRIPTION_ADD_FAILED = "PRESCRIPTION_ADD_FAILED";
	String PRESCRIPTION_READ_FAILED = "PRESCRIPTION_READ_FAILED";
	String PRESCRIPTION_REMOVE_FAILED = "PRESCRIPTION_REMOVE_FAILED";
	String PRESCRIPTION_MODIFY_FAILED = "PRESCRIPTION_MODIFY_FAILED";
	String OBSERVATION_ADD_FAILED = "OBSERVATION_ADD_FAILED";
	String OBSERVATION_READ_FAILED = "OBSERVATION_READ_FAILED";
	String OBSERVATION_MODIFY_FAILED = "OBSERVATION_MODIFY_FAILED";
	String CONTACT_READ_FAILED = "CONTACT_READ_FAILED";
	
	public final static String MEDICINE_ADD_FAILED = "MEDICINE_ADD_FAILED";
	public final static String MEDICINE_MODIFY_FAILED = "MEDICINE_MODIFY_FAILED";
	public final static String MEDICINE_REMOVE_FAILED = "MEDICINE_REMOVE_FAILED";
	public final static String BRAND_ADD_FAILED = "BRAND_ADD_FAILED";
	public final static String BRAND_MODIFY_FAILED = "BRAND_MODIFY_FAILED";
	public final static String BRAND_REMOVE_FAILED = "BRAND_REMOVE_FAILED";
	static String BRAND_READ_FAILED = "BRAND_READ_FAILED";
	static String MEDICINE_TYPE_READ_FAILED ="MEDICINE_TYPE_READ_FAILED";
	static String MEDICINE_READ_FAILED ="MEDICINE_READ_FAILED";
	static String CREATE_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";
	static String CREATE_RECEIVABLE_FAILED = "CREATE_RECEIVABLE_FAILED";
	
	String REFERENCE_DATA_READ_FAILED ="REFERENCE_DATA_READ_FAILED";
	
	
	public final static String ERROR_RUNNING_REPORT = "ERROR_RUNNING_REPORT";
	public static final String MARK_ASSIGNED_SERVICE_IS_BILLABE_FAILED = "MARK_ASSIGNED_SERVICE_IS_BILLABE_FAILED";
	public static final String IS_ELIGIBLE_FOR_CANCEL_FAILED = "IS_ELIGIBLE_FOR_CANCEL_FAILED";
}
