/**
 * 
 */
package in.wtc.hcis.bo.constants;

/**
 * @author Alok Ranjan
 *
 */
public interface ReferralConstants {
	String REFERENCE_TYPE_REFERRAL = "REF";
	String ENTITY_TYPE_REFERRAL = "REFERRAL";
	String REFERRAL_TYPE_LIST = "REFERRAL_TYPE_LIST";
	
	String REFERRAL_COMMISSION_TYPE_SERVICES = "SERVICES";
	String REFERRAL_COMMISSION_TYPE_APPOINTMENTS = "APPOINTMENTS";
	
	String REFERRAL_COMMISSION_IND_ABSOLUTE = "ABSOLUTE";
	String REFERRAL_COMMISSION_IND_PERCENTAGE = "PERCENTAGE";
	
	String REFERRAL_PAYABLE_ACCONUTED_YES = "Y";
	String REFERRAL_PAYABLE_ACCONUTED_NO = "N";
    String REFFERAL_TYPE_CONTEXT = "REFFERAL_TYPE"; 
    String PCT_ABS_IND_CONTEXT = "PCT_ABS_IND";
}
