/**
 * 
 */
package in.wtc.hcis.bo.constants;

/**
 * @author Ajit Kumar
 *
 */
public interface ReportsDetail {
	
	public static final String REPORTS_DIR_PATH = "REPORTS_DIR_PATH";
	public static final String PATIENT_CARD_REPORT_NAME = "PATIENT_CARD_REPORT_NAME";
	public static final String PATIENT_CARD_REPORT_FILENAME = "PATIENT_CARD_REPORT_FILENAME";

	public static final String PATIENT_ATTENDANT_CARD_REPORT_NAME = "PATIENT_ATTENDANT_CARD_REPORT_NAME";
	public static final String PATIENT_ATTENDANT_CARD_REPORT_FILENAME = "PATIENT_ATTENDANT_CARD_REPORT_FILENAME";

	public static final String PATIENT_VISIT_SLIP_REPORT_NAME = "PATIENT_VISIT_SLIP_REPORT_NAME";
	public static final String PATIENT_VISIT_SLIP_REPORT_FILENAME = "PATIENT_VISIT_SLIP_REPORT_FILENAME";

	public static final String PATIENT_BILL_REPORT_NAME = "PATIENT_BILL_REPORT_NAME";
	public static final String PATIENT_BILL_REPORT_FILENAME = "PATIENT_BILL_REPORT_FILENAME";

	public static final String PATINET_BILL_REPORT_PATH = "PATINET_BILL_REPORT_PATH";
	
	public static final String PATIENT_CONSULTATION_FEE_REPORT_NAME = "PATIENT_CONSULTATION_FEE_REPORT_NAME";
	public static final String PATIENT_CONSULTATION_FEE_REPORT_FILENAME = "PATIENT_CONSULTATION_FEE_REPORT_FILENAME";
	
	public static final String REGISTRATION_FEE_RECEIPT_REPORT_NAME="REGISTRATION_FEE_RECEIPT_REPORT_NAME";
	public static final String REGISTRATION_FEE_RECEIPT_FILE_NAME="REGISTRATION_FEE_RECEIPT_FILE_NAME";
	
	public static final String REFERRAL_COMMISSION_REPORT_NAME = "REFERRAL_COMMISSION_REPORT_NAME";
	public static final String REFERRAL_COMMISSION_REPORT_FILENAME = "REFERRAL_COMMISSION_REPORT_FILENAME";
	public static final String REPORT_DATASORCE_SESSION = "SESSION";
}
