package in.wtc.hcis.bo.constants;

public interface ScheduleManagerConstants {

	String IS_ACTIVE_TRUE ="Y";
	String IS_ACTIVE_FALSE ="N";
	
	String VACCINATION_TYPE = "VACCINATION_TYPE";
	String PERIOD_IND = "PERIOD_IND";
	String VACCINATION ="VACCINATION";
	String VACCINATION_ACTIVE_FLAG = "VACCINATION_ACTIVE_FLAG";
	String PAT_VACC_SCHEDULE_STATUS = "PAT_VACC_SCHEDULE_STATUS";
	String PAT_VACC_SCHEDULE_STATUS_COMPLETED = "COMPLETED";
	String PAT_VACC_SCHEDULE_STATUS_PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED";
	String PAT_VACC_SCHEDULE_STATUS_NOT_STARTED = "NOT_STARTED";
	String DELETE_FLAG_YES ="Y";
}
