/**
 * 
 */
package in.wtc.hcis.bo.constants;

/**
 * @author Alok Ranjan
 *
 */
public interface ServicesConstants {
	
	String SERVICE_PROCESS_NAME = "SERVICES";
	String SERVICE_SUBPROCESS_PACKAGE = "PACKAGE";
	String SERVICE_SUBPROCESS_SERVICE = "SERVICE";
	
	String SERVICE_ASSIGNED_FROM_OPD = "OPD";
	String SERVICE_ASSIGNED_FROM_DIRECT = "DIRECT";
	String SERVICE_ASSIGNED_FROM_IPD = "IPD";
	String SERVICE_ASSIGNED_FROM_EMEREGENCY = "EMEREGENCY";
	
	// Default values
	String DEFAULT_SERVICE_GROUP = "GENERAL";
	Integer DEFAULT_REQUESTED_UNITS = 1;
	Integer DEFAULT_BILLED_UNITS = 0;
	Integer DEFAULT_CANCELED_UNITS = 0;
	Integer DEFAULT_RENDERED_UNITS = 0;
	
	// Service status
	String SERVICE_STATUS_CREATED = "CREATED";
	String SERVICE_STATUS_ACTIVE = "ACTIVE";
	String SERVICE_STATUS_SUSPENDED = "SUSPENDED";
	String SERVICE_STATUS_EXPIRED = "EXPIRED";
	
	// Service package status
	String SERVICE_PACKAGE_CREATED = "CREATED";
	String SERVICE_PACKAGE_PUBLISHED = "PUBLISHED";
	String SERVICE_PACKAGE_ACTIVE = "ACTIVE";
	String SERVICE_PACKAGE_SUSPENDED = "SUSPENDED";
	String SERVICE_PACKAGE_EXPIRED = "EXPIRED";
	
	// Assigned service status
	String ASSIGNED_SERVICE_REQUESTED = "REQUESTED";
	String ASSIGNED_SERVICE_PARTRENDERED = "PARTRENDERED";
	String ASSIGNED_SERVICE_RENDERED = "RENDERED";
	String ASSIGNED_SERVICE_CANCELED = "CANCELED";
	String ASSIGNED_SERVICE_PARTCANCELED = "PARTCANCELED";
	String ASSIGNED_SERVICE_REPLACED = "REPLACED";
	String ASSIGNED_SERVICE_PARTREPLACED = "PARTREPLACED";
	String ASSIGNED_SERVICE_DELETED = "DELETED";
	String ASSIGNED_SERVICE_BILLED = "BILLED";
	
	// Assigned package status
	String ASSIGNED_PACKAGE_REQUESTED = "REQUESTED";
	String ASSIGNED_PACKAGE_RENDERED = "RENDERED";
	String ASSIGNED_PACKAGE_CANCELED = "CANCELED";
	String ASSIGNED_PACKAGE_DELETED = "DELETED";
	
	String CHARGE_OVERRIDE_LEVEL_PACKAGE = "P";
	String CHARGE_OVERRIDE_LEVEL_SERVICE = "S";
    String DISCOUNT_TYPE_ABSOLUTE  ="A";
    String DISCOUNT_TYPE_PERCENT  ="P";
    
    String PACKAGE_SUSPENSION_LEVEL_SERVICE = "S";
    String PACKAGE_SUSPENSION_LEVEL_PACKAGE = "P";
    
    //SERVICE TYPE CONSTANT
    
    String SERVICE_TYPE = "SERVICE_TYPE";
    
    //REQUISITION ORDER SATATUS
    
    String REQUISTION_ORDER_CREATED = "CREATED";
    
    //BILLABLE 
    String IS_BILLABLE_YES = "Y";
    String IS_BILLABLE_NO = "N";
    
    //PRICE UPDATE
    String INCREMENT_INDECATOR = "I";
    String DECREMENT_INDECATOR = "D";
    
    String AMOUNT_ABSOULUTE = "A";
    String AMOUNT_PERCENTAGE = "P";
	String PROCESSED_N = "N";
	String PROCESSED_Y = "Y";
	String PROCESS_SERVICE_PRICE_UPDATE = "Service price update process" ;
	
	String REQUISITION_STATUS_CREATED = "CREATED";
	String REQUISITION_STATUS_IN_PROGRESS= "IN_PROGRESS";
	String REQUISITION_STATUS_COMPLETED = "COMPLETED";
	String REQUISITION_STATUS_CANCELED = "CANCELED";
		
	
}
