/**
 * 
 */
package in.wtc.hcis.bo.appointment;

/**
 * @author Alok Ranjan
 *
 */
public interface AppointmentConstants {
	String BOOKED_APPOINTMENT = "BOOKED";
	String CONFIRMED_APPOINTMENT = "CONFIRMED";
	String CANCELED_APPOINTMENT = "CANCELLED";
	String RESCHEDULED_APPOINTMENT = "RESCHEDULED";
	String PATIENT_CAME_TO_VISIT = "TOVISIT";
	String PATIENT_VISITED = "VISITED";
	String DOCTOR_CAPTURED = "CAPTURED";
	String INVALID_ROSTER = "INVALID_ROSTER";
	String ROSTER_MODIFIED = "ROSTER_MODIFIED";
	
	String DEFAULT_APPOINTMENT_STATUS = "DEFAULT_APPOINTMENT_STATUS";
	String APPOINTMENT_SLOT_INTERVAL = "APPOINTMENT_SLOT_INTERVAL";
	String DEFAULT_BOOKING_TYPE = "DEFAULT_BOOKING_TYPE";
	
	String APPONITMENT_TYPE ="APPONITMENT_TYPE";
}
