/**
 * 
 */
package in.wtc.hcis.bo.common;

/**
 * @author Rohit
 * 
 */
public interface ApplicationErrors {
	String PATIENT_DOES_NOT_EXIST = "PATIENT_DOES_NOT_EXIST";
	String PATIENT_CANNNOT_BE_DELETED = "PATIENT CANNOT BE DELETED";
	String PATIENT_DETAILS_DOES_NOT_EXIST = "PATIENT_DETAILS_DOES_NOT_EXIST";
	String PATIENT_RETRIEVAL_FAILED = "PATIENT_RETRIEVAL_FAILED";
	String CREATE_APPOINTMENT_FAILED = "CREATE_APPOINTMENT_FAILED";
	String CREATE_APPOINTMENT_HISTORY_FAILED = "CREATE_APPOINTMENT_HISTORY_FAILED";
	String CANCEL_APPOINTMENT_FAILED = "CANCEL_APPOINTMENT_FAILED";
	String REMOVE_APPOINTMENTS_FAILED = "REMOVE_APPOINTMENTS_FAILED";
	String RESCHEDULE_APPOINTMENTS_FAILED = "RESCHEDULE_APPOINTMENTS_FAILED";
	String READ_APPOINTMENT_FAILED = "READ_APPOINTMENT_FAILED";
	String READ_APPOINTMENT_STATUS_FAILED = "READ_APPOINTMENT_STATUS_FAILED";
	String UPDATE_APPOINTMENT_STATUS_FAILED ="UPDATE_APPOINTMENT_STATUS_FAILED";
	String READ_BOOKING_TYPE_FAILED = "READ_BOOKING_TYPE_FAILED";
	String READ_DOCTOR_FAILED = "READ_DOCTOR_FAILED";
	String READ_PATIENT_FAILED = "READ_PATIENT_FAILED";
	String READ_ROSTER_FAILED = "READ_ROSTER_FAILED";
	String READ_ROOM_FAILED = "READ_ROOM_FAILED";
	String CREATE_ROSTER_FAILED = "CREATE_ROSTER_FAILED";
	String UPDATE_ROSTER_FAILED = "UPDATE_ROSTER_FAILED";
	String REMOVE_ROSTER_FAILED = "REMOVE_ROSTER_FAILED";
	String NO_ROSTER_FOUND = "NO_ROSTER_FOUND";
	String READ_DEPARTMENT_FAILED = "READ_DEPARTMENT_FAILED";
	String IP_REMOVE_HOSPITAL_BED = "IP_REMOVE_HOSPITAL_BED";
	String IP_REMOVE_BED_ENVELOPE = "IP_REMOVE_BED_ENVELOPE";
	String IP_REMOVE_BED_POOL = "IP_REMOVE_BED_POOL";
	String READ_BEDENVELOPE_FAILED = "READ_BEDENVELOPE_FAILED";
	String READ_BEDMASTER_FAILED = "READ_BEDMASTER_FAILED";
	String READ_BEDPOOL_FAILED = "READ_BEDPOOL_FAILED";
	String READ_BEDPOOL_UNIT_TYPE_FAILED = "READ_BEDPOOL_UNIT_TYPE_FAILED";
	String READ_BEDRESERVATION_FAILED = "READ_BEDRESERVATION_FAILED";
	String READ_BEDSTATUS_FAILED = "READ_BEDSTATUS_FAILED";
	String READ_BEDTYPE_FAILED = "READ_BEDTYPE_FAILED";
	String READ_NURSING_UNIT_FAILED = "READ_NURSING_UNIT_FAILED";
	String READ_NURSING_UNIT_TYPE_FAILED = "READ_NURSING_UNIT_TYPE_FAILED";
	String READ_ADMISSION_FAILED = "READ_ADMISSION_FAILED";
	String READ_COUNTRY_FAILED = "READ_COUNTRY_FAILED";
	String READ_STATE_FAILED = "READ_STATE_FAILED";

	String ADD_BED_FAILED = "ADD_BED_FAILED";
	String ASSIGN_BED_FAILED = "ASSIGN_BED_FAILED";
	String TRANSFER_TO_NEW_BED_FAILED = "TRANSFER_TO_NEW_BED_FAILED";
	String RELEASE_BED_FAILED = "RELEASE_BED_FAILED";
	String BED_BILLING_FAILLED = "BED_BILLING_FAILLED";
	String ADD_BED_BILLING_HISTORY_FAILED = "ADD_BED_BILLING_HISTORY_FAILED";
	String ADD_BED_ENVELOPE_FAILED = "ADD_BED_ENVELOPE_FAILED";
	String ADD_BED_POOL_FAILED = "ADD_BED_POOL_FAILED";
	String READ_ALLBEDS_FAILED = "READ_ALLBEDS_FAILED";
	String READ_BOOKING_DETAILS_FAILED = "READ_BOOKING_DETAILS_FAILED";
	String READ_BED_DETAILS_FAILED = "READ_BED_DETAILS_FAILED";
	String MODIFY_BED_BOOKING_THRESHOLD_FAILED = "MODIFY_BED_BOOKING_THRESHOLD_FAILED";
	String MODIFY_BED_FAILED = "MODIFY_BED_FAILED";
	String MODIFY_BED_ENVELOPE_FAILED = "MODIFY_BED_ENVELOPE_FAILED";
	String MODIFY_BED_POOL_FAILED = "MODIFY_BED_POOL_FAILED";
	String REMOVE_BED_FAILED = "REMOVE_BED_FAILED";
	String READ_BED_SPECIAL_FEATURE_FAILED = "READ_BED_SPECIAL_FEATURE_FAILED";
	String READ_DOCTOR_ORDER_GROUP_FAILED = "READ_DOCTOR_ORDER_GROUP_FAILED";
	String READ_DOCTOR_ORDER_TEMPLATE_FAILED = "READ_DOCTOR_ORDER_TEMPLATE_FAILED";
	String READ_DOCTOR_TYPE_FAILED = "READ_DOCTOR_TYPE_FAILED";
	String READ_DOCTOR_ORDER_FAILED = "READ_DOCTOR_ORDER_FAILED";
	String READ_DOCTOR_ORDER_STATUS_FAILED = "READ_DOCTOR_ORDER_STATUS_FAILED";
	String APPROVE_ORDER_FAILED = "APPROVE_ORDER_FAILED";
	String READ_ACTION_STATUS_FAILED = "READ_ACTION_STATUS_FAILED";
	String READ_SERVICE_FAILED = "READ_SERVICE_FAILED";
	String READ_SERVICE_PACKAGE_FAILED = "READ_SERVICEPACKAGE_FAILED";
	String READ_ACTIVITY_TYPE_FAILED = "READ_ACTIVITY_TYPE_FAILED";
	String READ_ADMISSION_STATUS_FAILED = "READ_ADMISSION_STATUS_FAILED";
	String CREATE_DOCTOR_ORDER_FAILED = "CREATE_DOCTOR_ORDER_FAILED";
	String CREATE_DOCTOR_ORDER_TYPE_FAILED = "CREATE_DOCTOR_ORDER_TYPE_FAILED";
	String MODIFY_ORDER_TEMPLATE_FAILED = "MODIFY_ORDER_TEMPLATE_FAILED";
	String MODIFY_ORDER_GROUP_FAILED = "MODIFY_ORDER_GROUP_FAILED";
	String MODIFY_DOCTOR_ORDER_FAILED = "MODIFY_DOCTOR_ORDER_FAILED";
	String REMOVE_ORDER_TEMPLATE_FAILED = "REMOVE_ORDER_TEMPLATE_FAILED";
	String REMOVE_DOCTOR_ORDER_GROUP_FAILED = "REMOVE_DOCTOR_ORDER_GROUP_FAILED";
	String REMOVE_DOCTOR_ORDER_FAILED = "REMOVE_DOCTOR_ORDER_FAILED";
	String READ_SERVICES_WITH_ORDER_FAILED = "READ_SERVICES_WITH_ORDER_FAILED";

	String READ_ADMISSION_ENTRY_POINT_FAILED = "READ_ADMISSION_ENTRY_POINT_FAILED";

	String ACTIVE_ADMISSION_ALREADY_EXIST = "ACTIVE_ADMISSION_ALREADY_EXIST";
	String ACTIVE_ADMISSION_DOES_NOT_EXIST = "ACTIVE_ADMISSION_DOES_NOT_EXIST";
	String DISCHARGE_ORDER_ALREADY_EXIST = "DISCHARGE_ORDER_ALREADY_EXIST";
	String DOCTOR_ORDER_ALREADY_COMPLETED = "DOCTOR_ORDER_ALREADY_COMPLETED";
	String READ_DISCHARGE_TYPE_FAILED = "READ_DISCHARGE_TYPE_FAILED";
	String READ_DISCHARGE_ORDER_FAILED = "READ_DISCHARGE_ORDER_FAILED";
	String CREATE_DISCHARGE_ENTRY_FAILED = "CREATE_DISCHARGE_ENTRY_FAILED";
	String DISCHARGE_OPERATION_FAILED = "DISCHARGE_OPERATION_FAILED"; 

	String ADD_CLAIM_SPONSOR_FAILED = "ADD_CLAIM_SPONSOR_FAILED";
	String ADD_INSURER_FAILED = "ADD_INSURER_FAILED";
	String CREATE_CLAIM_REQUEST_FAILED = "CREATE_CLAIM_REQUEST_FAILED";
	String MODIFY_CLAIM_REQUEST_FAILED = "MODIFY_CLAIM_REQUEST_FAILED";
	String MODIFY_INSURANCE_PLAN_FAILED = "MODIFY_INSURANCE_PLAN_FAILED";
	String MODIFY_CLAIM_SPONSOR_FAILED = "MODIFY_CLAIM_SPONSOR_FAILED";
	String MODIFY_INSURER_FAILED = "MODIFY_INSURER_FAILED";
	String READ_CLAIM_REQUEST_FAILED = "READ_CLAIM_REQUEST_FAILED";
	String READ_CLAIM_SPONSOR_FAILED = "READ_CLAIM_SPONSOR_FAILED";
	String READ_CREDIT_CLASS_FAILED = "READ_CREDIT_CLASS_FAILED";
	String READ_INSURANCE_PLAN_FAILED = "READ_INSURANCE_PLAN_FAILED";
	String READ_SPONSOR_TYPE_FAILED = "READ_SPONSOR_TYPE_FAILED";
	String READ_SPONSOR_CLAIM_STATUS_FAILED = "READ_SPONSOR_CLAIM_STATUS_FAILED";
	String REMOVE_SPONSOR_SLA_FAILED = "REMOVE_SPONSOR_SLA_FAILED";
	String REMOVE_SPONSOR_FAILED = "REMOVE_SPONSOR_FAILED";
	String REMOVE_INSURANCE_PLAN_FAILED = "REMOVE_INSURANCE_PLAN_FAILED";
	String READ_INSURER_FAILED = "READ_INSURER_FAILED";
	String REMOVE_INSURER_FAILED = "REMOVE_INSURER_FAILED";
	String REMOVE_CLAIM_REQUEST_FAILED = "REMOVE_CLAIM_REQUEST_FAILED";

	String READ_DISEASE_FAILED = "READ_DISEASE_FAILED";
	
	String READ_ATTRIBUTE_FAILED = "READ_ATTRIBUTE_FAILED";
	String VALUE_REQUIRE_FOR_MANDATORY_FIELD = "VALUE_REQUIRE_FOR_MANDATORY_FIELD";
	String READ_RESERVAION_STATUS_FAILED = "READ_RESERVAION_STATUS_FAILED";
	String ADDMISSION_REQ_NBR_REQUIRED = "ADDMISSION_REQ_NBR_REQUIRED";
	
	String MODIFY_BED_REERVATION_FAILED = "MODIFY_BED_REERVATION_FAILED";
	
	String MODIFY_ADMISSION_FAILED = "MODIFY_ADMISSION_FAILED";
	String CONFIRM_ADMISSION_FAILED = "CONFIRM_ADMISSION_FAILED";
	
	String CREATE_ACCOUNT_FAILED = "CREATE_ACCOUNT_FAILED";
	String CREATE_RECEIVABLE_FAILED = "CREATE_RECEIVABLE_FAILED";
	String CREATE_RECEIPT_FALIED ="CREATE_RECEIPT_FALIED";
	String REMOVE_ACCOUNT_FAILED = "REMOVE_ACCOUNT_FAILED";
	String READ_RECEIVABLE_FAILED = "READ_RECEIVABLE_FAILED";
	String READ_RECEIPT_FALIED ="READ_RECEIPT_FALIED";
	
	String NULL_OBJECT_ENCOUNTERED ="NULL_OBJECT_ENCOUNTERED";
	
	String ADD_SCHEDULE_FAILED = "ADD_SCHEDULE_FAILED";
	String MODIFY_VACCINATION_SCHEDULE_FAILED ="MODIFY_VACCINATION_SCHEDULE_FAILED";
	String REMOVE_VACCINATION_SCHEDULE_FAILED = "REMOVE_VACCINATION_SCHEDULE_FAILED";
	
	String ERROR_ENCOUNTERED = "ERROR_ENCOUNTERED";
	String DATABASE_ERROR = "DATABASE_ERROR";
	
	String ERROR_RUNNING_REPORT = "ERROR_RUNNING_REPORT";
	
	String READ_SYSTEM_CONFIGURATION_FAILED = "READ_SYSTEM_CONFIGURATION_FAILED";
	String UPDATE_SYSTEM_CONFIGURATION_FAILED = "UPDATE_SYSTEM_CONFIGURATION_FAILED";
	
	String REFERRAL_READ_FAILED = "REFERRAL_READ_FAILED";
	String REFERRAL_COMMISSION_TYPE_READ_FAILED = "REFERRAL_COMMISSION_TYPE_READ_FAILED";
	String REFERRAL_DELETE_FAILED = "REFERRAL_DELETE_FAILED";
	String REFERRAL_RUN_REPORT_FAILED = "REFERRAL_RUN_REPORT_FAILED";
	String REFERRAL_MODIFY_FAILED = "REFERRAL_MODIFY_FAILED";
	String REFERRAL_SAVE_FAILED = "REFERRAL_SAVE_FAILED";
	String REFERRAL_TYPE_READ_FAILED = "REFERRAL_TYPE_READ_FAILED";
	String REFERRAL_PROCESS_COMMISSION_FAILED = "REFERRAL_PROCESS_COMMISSION_FAILED";
	String REFERRAL_COMMISSION_PROCESS_READ_FAILED = "REFERRAL_COMMISSION_PROCESS_READ_FAILED";
	String REFERRAL_COMMISSTION_TYPE_IND_READ_FAILED = "REFERRAL_COMMISSTION_TYPE_IND_READ_FAILED";
	
	String REFERENCE_DATA_READ_FAILED ="REFERENCE_DATA_READ_FAILED";
	
	String VACCINATION_READ_FAILED = "VACCINATION_READ_FAILED";
	String READ_VACCINATION_SCHEDULE_DETAILS_FAILED = "READ_VACCINATION_SCHEDULE_DETAILS_FAILED";
	
	String SPECIALITY_READ_FAILED = "SPECIALITY_READ_FAILED";
	String READ_PAT_VACC_SCHEDULE_FAILED = "READ_PAT_VACC_SCHEDULE_FAILED";
	String READ_PAT_VACC_SCHEDULE_DETAILS_FAILED = "READ_PAT_VACC_SCHEDULE_DETAILS_FAILED";
	String VACCINATION_SCHEDULE_READ_FAILED = "VACCINATION_SCHEDULE_READ_FAILED";
	String ADD_PAT_VACC_SCHEDULE_FAILED = "ADD_PAT_VACC_SCHEDULE_FAILED";
	String DELETE_PAT_VACC_SCHEDULE_DETAILS_FAILED = "DELETE_PAT_VACC_SCHEDULE_DETAILS_FAILED";
	String DELETE_PAT_VACC_SCHEDULE_FAILED = "DELETE_PAT_VACC_SCHEDULE_FAILED";
	String CANCEL_PAT_VACC_SCHEDULE_DETAIL_FAILED = "CANCEL_PAT_VACC_SCHEDULE_DETAIL_FAILED";
	String CANCEL_PAT_VACC_SCHEDULE_FAILED = "CANCEL_PAT_VACC_SCHEDULE_FAILED";
	String VACCINATION_SCHEDULE_DETAILS_READ_FAILED = "VACCINATION_SCHEDULE_DETAILS_READ_FAILED";
	
	String CREATE_BP_FAILED = "CREATE_BP_FAILED";
	String MODIFY_BP_FAILED = "MODIFY_BP_FAILED";
	String READ_BP_FAILED="READ_BP_FAILED";
	String ASSIGNED_SERVICE_READ_FAILED = "ASSIGNED_SERVICE_READ_FAILED";
	
	String DATE_DIM_READ_FAILED = "DATE_DIM_READ_FAILED";
	
	String ENTITY_SAVE_FAILED = "ENTITY_SAVE_FAILED";
	String ENTITY_MODIFY_FAILED = "ENTITY_MODIFY_FAILED";
	String ENTITY_SEARCH_FAILED = "ENTITY_SEARCH_FAILED";
	
	String CHECK_LIST_ADD_FAILED = "CHECK_LIST_ADD_FAILED";
	String CHECK_LIST_DETAIL_ADD_FAILED = "CHECK_LIST_DETAIL_ADD_FAILED";
	String CHECK_LIST_DETAIL_REMOVE_FAILED = "CHECK_LIST_DETAIL_REMOVE_FAILED";
	String CHECK_LIST_DETAIL_MODIFY_FAILED = "CHECK_LIST_DETAIL_MODIFY_FAILED";
	String CHECK_LIST_GROUP_READ_FAILED = "CHECK_LIST_GROUP_READ_FAILED";
	String CHECK_LIST_DETAIL_READ_FAILED = "CHECK_LIST_DETAIL_READ_FAILED";
	
	
	String VITAL_FIELD_READ_FAILED = "VITAL_FIELD_READ_FAILED";
	String PATIENT_VITAL_READ_FAILED = "PATIENT_VITAL_READ_FAILED";
	String TRANSITION_STATUS_READ_FAILED = "TRANSITION_STATUS_READ_FAILED";
}
