package in.wtc.hcis.ot.bl.constant;

public interface OTErrors {
	
	String OPERATON_THEATRE_ADD_FAILED = "OPERATON_THEATRE_ADD_FAILED";
	String OPERATON_THEATRE_MODIFY_FAILED = "OPERATON_THEATRE_MODIFY_FAILED";
	String OPERATON_THEATRE_READ_FAILED = "OPERATON_THEATRE_READ_FAILED";
	String OPERATON_THEATRE_ADD_SURGERY_ASSOCIATION_FAILED = "OPERATON_THEATRE_ADD_SURGERY_ASSOCIATION_FAILED";
	String OPERATON_THEATRE_REMOVE_SURGERY_ASSOCIATION_FAILED = "OPERATON_THEATRE_REMOVE_SURGERY_ASSOCIATION_FAILED";
	String OPERATON_THEATRE_REMOVE_FAILED = "OPERATON_THEATRE_REMOVE_FAILED";
	String SURGERY_STATUS_TIME_DETAIL_READ_FAILED = "SURGERY_STATUS_TIME_DETAIL_READ_FAILED";
	String SURGERY_ADD_FAILED = "SURGERY_ADD_FAILED";
	String SURGERY_STATUS_TIME_DETAIL_ADD_FAILED = "SURGERY_STATUS_TIME_DETAIL_ADD_FAILED";
	String SURGERY_STATUS_TIME_DETAIL_REMOVE_FAILED = "SURGERY_STATUS_TIME_DETAIL_REMOVE_FAILED";
	String OPERATON_THEATRE_BOOKING_FAILED = "OPERATON_THEATRE_BOOKING_FAILED";
}
