source allergies.sql
source appointment_status.sql
source app_entities.sql
source blood_group.sql
source booking_type.sql
source brand.sql
source change_reason.sql
source contact_type.sql
source country.sql
source department.sql
source duration.sql
source especialty.sql
source gender.sql
source id_proofs.sql
source marital.sql
source medicine_type.sql
source mother_tongue.sql
source nationality.sql
source patient_category.sql
source patient_rating.sql
source registration_status.sql
source registration_type.sql
source relation.sql
source religion.sql
source reminder_options.sql
source room.sql
source saluation.sql
source sample_master.sql
source service_status.sql
source state.sql
source treatment_reason.sql
source status.sql
source service_package_status.sql
source assigned_service_status.sql
source assigned_package_status.sql
source immunization.sql
source system_parameter.sql
source reference_data_list.sql
source referral_commission_process.sql
source dept_especiality_assoc.sql
source report_param.sql
source date_dim.sql