INSERT INTO `report_param` (`REPORT_CODE`, `WIDGET_NAME`, `WIDGET_LABEL`, `WIDGET_LENGTH`, `XTYPE`, `DATA_PROVIDER_METHOD`, `REQUIRED_FLAG`, `WIDGET_SEQ_NBR`) VALUES
('AppointmentSummary', 'fromDate', 'From', NULL, 'date', NULL, 'N', 1),
('AppointmentSummary', 'toDate', 'To', NULL, 'date', NULL, 'N', 2),
('DailyAppointments', 'date', 'For date', NULL, 'date', NULL, 'N', 1),
('DailyAppointments', 'departmentCode', 'Department', NULL, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDepartments', 'N', 2),
('DailyAppointments', 'doctorId', 'Doctor Name', NULL, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDoctors', 'N', 3),
('DailyPatientWaitTime', 'date', 'For date', NULL, 'date', NULL, 'Y', NULL),
('DailyPatientWaitTime', 'departmentCode', 'Department', NULL, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDepartments', 'N', NULL),
('DailyReceiptStatement', 'fromDate', 'From', NULL, 'date', NULL, 'N', NULL),
('DailyReceiptStatement', 'toDate', 'To', NULL, 'date', NULL, 'N', NULL),
('DepartmentWiseRevenue', 'departmentCode', 'Department', 90, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDepartments', 'N', 1),
('DepartmentWiseRevenue', 'fromDate', 'Date(from)', 90, 'date', NULL, 'N', 2),
('DepartmentWiseRevenue', 'toDate', 'Date(to)', 90, 'date', NULL, 'N', 3),
('DoctorwiseRevenueDetail', 'doctorId', 'Doctor', NULL, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDoctors', 'N', 3),
('DoctorwiseRevenueDetail', 'fromDate', 'From', NULL, 'date', NULL, 'N', 1),
('DoctorwiseRevenueDetail', 'toDate', 'To', NULL, 'date', NULL, 'N', 2),
('DoctorWiseServiceAssignment', 'doctorId', 'Doctor', NULL, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDoctors', 'N', 3),
('DoctorWiseServiceAssignment', 'fromDate', 'From', NULL, 'date', NULL, 'N', 1),
('DoctorWiseServiceAssignment', 'toDate', 'To', NULL, 'date', NULL, 'N', 2),
('OPDInflow', 'departmentCode', 'Department', NULL, 'MVL', 'in.wtc.hcis.bo.common.DataModelManager.getDepartments', 'N', 3),
('OPDInflow', 'fromDate', 'From', NULL, 'date', NULL, 'N', 1),
('OPDInflow', 'toDate', 'To', NULL, 'date', NULL, 'N', 2),
('OPDPatientBill', 'billNbr', 'Bill Number', NULL, 'string', NULL, 'Y', NULL),
('ServiceWiseRevenue', 'fromDate', 'From', NULL, 'date', NULL, 'N', 1),
('ServiceWiseRevenue', 'toDate', 'To', NULL, 'date', NULL, 'N', 2);
