/**
 * 
 */
package in.wtc.lims.constant;

/**
 * @author Bhavesh
 *
 *This interface contains all the constants related to LIMS error and exceptions
 */
public interface LimsErrors {

	String TECHNIQUE_READ_FAILED = "TECHNIQUE_READ_FAILED";
	String SEARCH_REQUISITION_FAILED = "SEARCH_REQUISITION_FAILED";
	String GET_REQUISITION_ORDER_DETAIL_FAILED = "GET_REQUISITION_ORDER_DETAIL_FAILED";
	String REQUISITION_ORDER_CANCEL_FAILED = "REQUISITION_ORDER_CANCEL_FAILED";
	String REQUISITION_ORDER_READ_FAILED = "REQUISITION_ORDER_READ_FAILED";
	String TECHNIQUE_ADD_FAILED = "TECHNIQUE_ADD_FAILED";
	String TECHNIQUE_MODIFY_FAILED = "TECHNIQUE_MODIFY_FAILED";
	String TECHNIQUE_DELETE_FAILED = "TECHNIQUE_DELETE_FAILED";
	

	String LAB_ADD_FAILED = "LAB_ADD_FAILED";
	
	String LAB_DETAILS_READ_FAILED = "LAB_DETAILS_READ_FAILED";
	
	String REFERENCE_DATA_READ_FAILED = "REFERENCE_DATA_READ_FAILED";
	
	String HOSPITAL_DETAILS_READ_FAILED = "HOSPITAL_DETAILS_READ_FAILED";
	
	String LAB_SEARCH_FAILED = "LAB_SEARCH_FAILED";
	
	String CONTACT_DETAILS_READ_FAILED = "CONTACT_DETAILS_READ_FAILED";
	
	String LAB_DETAILS_DELETE_FAILED = "LAB_DETAILS_DELETE_FAILED";
	String LAB_TEST_ATTRIBUTE_READ_FAILED = "LAB_TEST_ATTRIBUTE_READ_FAILED";
	String LAB_TEST_ATTRIBUTE_ADD_FAILED = "LAB_TEST_ATTRIBUTE_ADD_FAILED";
	String LAB_TEST_ATTRIBUTE_MODIFY_FAILED = "LAB_TEST_ATTRIBUTE_MODIFY_FAILED";
	String LAB_TEST_ADD_FAILED = "LAB_TEST_ADD_FAILED";
	String LAB_TEST_READ_FAILED = "LAB_TEST_READ_FAILED";
	String LAB_TEST_MODIFY_FAILED = "LAB_TEST_MODIFY_FAILED";
	String LAB_SPECIMEN_READ_FAILED = "LAB_SPECIMEN_READ_FAILED";
	String LAB_TEMPLATE_WIDGET_READ_FAILED = "LAB_TEMPLATE_WIDGET_READ_FAILED";
	String TEMPLATE_WIDGET_ADD_FAILED = "TEMPLATE_WIDGET_ADD_FAILED";
	String TEMPLATE_READ_FAILED = "TEMPLATE_READ_FAILED";
	String READ_WIDGET_FOR_TEMPLATE_FAILED = "READ_WIDGET_FOR_TEMPLATE_FAILED";
	String ADD_TEST_TEMPLATE_FAILED = "ADD_TEST_TEMPLATE_FAILED";
	String MODIFY_TEST_TEMPLATE_FAILED = "MODIFY_TEST_TEMPLATE_FAILED";
	String GET_WIDGET_FOR_TEST_FAILED = "GET_WIDGET_FOR_TEST_FAILED";
	String GET_VALUE_FOR_PROPERTY_FAILED = "GET_VALUE_FOR_PROPERTY_FAILED";
	String CREATE_PATIENT_LAB_TEST_DETAIL_FAILED = "CREATE_PATIENT_LAB_TEST_DETAIL_FAILED";
	String LAB_PATIENT_TEST_DETAIL_READ_FAILED = "LAB_PATIENT_TEST_DETAIL_READ_FAILED";
	String COLLECTION_POINT_ADD_FAILED = "COLLECTION_POINT_ADD_FAILED";
	String COLLECTION_POINT_READ_FAILED = "COLLECTION_POINT_READ_FAILED";
	String COLLECTION_POINT_MODIFY_FAILED = "COLLECTION_POINT_MODIFY_FAILED";
	String PATIENT_LAB_TEST_DETAIL_MODIFY_FAILED = "PATIENT_LAB_TEST_DETAIL_MODIFY_FAILED";
	String PATIENT_LAB_TEST_DETAIL_READ_FAILED  = "PATIENT_LAB_TEST_DETAIL_READ_FAILED";
	String READ_TEST_RESULT_HISTORYL_FAILED = "READ_TEST_RESULT_HISTORYL_FAILED";
	String LAB_TEST_ATTRIBUTE_REMOVE_FAILED = "LAB_TEST_ATTRIBUTE_REMOVE_FAILED";

}
