package in.wtc.lims.constant;

public interface RequisitionConstant {
	
	String LAB_TEST_SERVICE_TYPE = "LABORATORY";
	String REQUISITION_STATUS_CREATED = "CREATED";
	String REQUISITION_STATUS_BILLED = "BILLED";
	String REQUISITION_STATUS_PAID = "PAID";
	String REQUISITION_STATUS_RENDERED = "RENDERED";
	String REQUISITION_STATUS_PARTRENDERED = "PARTRENDERED";
	String REQUISITION_STATUS_CANCELLED = "CANCELED";

	String CONTEXT_TEST_REQUISITION_STATUS = "TEST_REQUISITION_STATUS";
	String CONTEXT_REFERENCE_TYPE = "REFERENCE_TYPE";
	
}
