/**
 * 
 */
package in.wtc.hcis.bm.base;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * @author Bhavesh
 *
 *This BM is meant for only updating the price details for multiple service and packages at one go.
 *
 *This BM contains update price of the services at 2 level.
 *Assumption  is that if UI is calculating new applicable price for each service then it should put the corresponding 
 *price in the "servicePriceMap". Otherwise it will be calculated at BL layer by keeping details given at the BM it self (Not  the map).
 *
 */
@SuppressWarnings("serial")
public class ServicePriceUpdateBM implements Serializable {


	private Double updateAmount;
	private String pectAbsInd;						//'P' for percentage and 'A' for absolute
	private String increDecreInd;					// 'I' to increase and 'D' to decrease
	private Date   effectiveFromDt;
	private Date   effectiveToDt;					//Will be generated by BL layer
	
	private Map<String,String> servicePriceMap;		//Map of serviceCode and price

	private String userId;
	
	
	public ServicePriceUpdateBM() {
		// TODO Auto-generated constructor stub
	}


	public Double getUpdateAmount() {
		return updateAmount;
	}


	public void setUpdateAmount(Double updateAmount) {
		this.updateAmount = updateAmount;
	}




	public String getIncreDecreInd() {
		return increDecreInd;
	}


	public void setIncreDecreInd(String increDecreInd) {
		this.increDecreInd = increDecreInd;
	}


	public Date getEffectiveFromDt() {
		return effectiveFromDt;
	}


	public void setEffectiveFromDt(Date effectiveFromDt) {
		this.effectiveFromDt = effectiveFromDt;
	}


	public Date getEffectiveToDt() {
		return effectiveToDt;
	}


	public void setEffectiveToDt(Date effectiveToDt) {
		this.effectiveToDt = effectiveToDt;
	}


	public Map<String, String> getServicePriceMap() {
		return servicePriceMap;
	}


	public void setServicePriceMap(Map<String, String> servicePriceMap) {
		this.servicePriceMap = servicePriceMap;
	}


	public String getUserId() {
		return userId;
	}


	public void setUserId(String userId) {
		this.userId = userId;
	}


	public String getPectAbsInd() {
		return pectAbsInd;
	}


	public void setPectAbsInd(String pectAbsInd) {
		this.pectAbsInd = pectAbsInd;
	}

	
}
