
function getDoctorDetailsRecordType() {

var doctorDetailsRecordType = Ext.data.Record.create([
    {name: "doctorId", type: "string", mapping:'doctorDetail.doctor.code'},
    {name: "personaldetailsreligion", type: "string", mapping:'doctorDetail.religion.description'},
    {name: "personaldetailsTitle", type: "string", mapping:'saluationCode.description'},
    {name: "personaldetailsGender", type: "string", mapping:'doctorDetail.gender.description'},
    {name: "personaldetailsBloodgroup", type: "string", mapping:'doctorDetail.bloodGroup.description'},
    {name: "personaldetailsIdproof", type: "string", mapping:'doctorDetail.idProof.description'},
    {name: "personaldetailsMeritialStatus", type: "string", mapping:'doctorDetail.marital.description'},
    {name: "personaldetailsNationality", type: "string", mapping:'doctorDetail.nationality.description'},
    {name: "personaldetailsNationalityCode", type: "string", mapping:'doctorDetail.nationality.code'},
    {name: "personaldetailsreligionCode", type: "string", mapping:'doctorDetail.religion.code'},
    {name: "personaldetailsTitleCode", type: "string", mapping:'saluationCode.code'},
    {name: "personaldetailsGenderCode", type: "string", mapping:'doctorDetail.gender.code'},
    {name: "personaldetailsBloodgroupCode", type: "string", mapping:'doctorDetail.bloodGroup.code'},
    {name: "personaldetailsIdproofCode", type: "string", mapping:'doctorDetail.idProof.code'},
    {name: "personaldetailsMeritialStatusCode", type: "string", mapping:'doctorDetail.marital.code'},
    {name: "personaldetailsFirstname", type: "string", mapping:'firstName'},
    {name: "personaldetailsMiddleName", type: "string", mapping:'middleName'},
    {name: "personaldetailsLastname", type: "string", mapping:'lastName'},
    {name: "personaldetailsparmanentdoctorChk", type: "bool", mapping:'doctorDetail.permanent'},
    {name: "personaldetailsJoiningdate", type: "date", mapping:'doctorDetail.joiningDt'},
    {name: "personaldetailsLeavingDate", type: "date", mapping:'doctorDetail.leavingDt'},
    {name: "personaldetailsDateOfBirth", type: "date", mapping:'doctorDetail.dob'},
    {name: "personaldetailsHeight", type: "string", mapping:'doctorDetail.height'},
    {name: "personaldetailsWeight", type: "string", mapping:'doctorDetail.weight'},
    {name: "personaldetailsfatherhusbandname", type: "string", mapping:'doctorDetail.fatherHusbandName'},
    {name: "personaldetailsIdno", type: "string", mapping:'doctorDetail.idNumber'},
    {name: "personaldetailsValidupto", type: "date", mapping:'doctorDetail.idValidUpto'},
    {name: "personaldetailsBloodGroupId", type: "string", mapping:'doctorDetail.bloodDonorId'},
    
    {name: "experience", type: "string", mapping:'doctorDetail.workExperience'},
    {name: "knownLanguages", type: "string", mapping:'doctorDetail.knownLanguages'},
    {name: "qualification", type: "string", mapping:'doctorDetail.qualification'},
    {name: "referredBy", type: "string", mapping:'doctorDetail.referredBy'},
    
    {name: "doctorSpeciality", type: "string", mapping:'doctorEspecialty.especialtyCode.description'},
    {name: "doctorDepartmentname", type: "string", mapping:'doctorEspecialty.departmentCode.description'},
    {name: "doctorRoomno", type: "string", mapping:'doctorEspecialty.roomCode.description'},
    {name: "doctorSpecialityCode", type: "string", mapping:'doctorEspecialty.especialtyCode.code'},
    {name: "doctorDepartmentnameCode", type: "string", mapping:'doctorEspecialty.departmentCode.code'},
    {name: "doctorRoomnoCode", type: "string", mapping:'doctorEspecialty.roomCode.code'},
    {name: "doctorJoiningdate", type: "date", mapping:'doctorEspecialty.joiningDt'},
    {name: "doctorleavingDate", type: "date", mapping:'doctorEspecialty.leavingDt'},
    {name: "doctorConsultationcharges", type: "float", mapping:'doctorEspecialty.consultationCharge'},
    {name: "followupfee", type: "float", mapping:'doctorEspecialty.followupCharge'},
    {name: "followupDays", type: "int", mapping:'doctorEspecialty.followupDay'},
    {name: "followupVisits", type: "int", mapping:'doctorEspecialty.followupVisit'},
    
     {name: "currentcontactId", type: "int", mapping:'currentContactDetail.contactDetailsCode'},
     {name: "currenthousename", type: "string", mapping:'currentContactDetail.houseNumber'},
     {name: "currentplacestreet", type: "string", mapping:'currentContactDetail.street'},
     {name: "currentcitydistrict", type: "string", mapping:'currentContactDetail.city'},
     {name: "currentpincode", type: "string", mapping:'currentContactDetail.pincode'},
     {name: "currentphonenumber", type: "string", mapping:'currentContactDetail.phoneNumber'},
     {name: "currentmobilenumber", type: "string", mapping:'currentContactDetail.mobileNumber'},
     {name: "currentfaxnumber", type: "string", mapping:'currentContactDetail.faxNumber'},
     {name: "currentemailaddress", type: "string", mapping:'currentContactDetail.email'},
     {name: "currentdurationodstay", type: "string", mapping:'currentContactDetail.stayDuration'},
     {name: "currentcountry", type: "string", mapping:'currentContactDetail.country.description'},
     {name: "currentstate", type: "string", mapping:'currentContactDetail.state.description'},
     {name: "currentcountryCode", type: "string", mapping:'currentContactDetail.country.code'},
     {name: "currentstateCode", type: "string", mapping:'currentContactDetail.state.code'},
     {name: "currentcontactType", type: "string", mapping:'currentContactDetail.contactType.code'},
     
     {name: "emergencycontactId", type: "int", mapping:'emergencyContactDetail.contactDetailsCode'},
     {name: "emergencyFristname", type: "string", mapping:'emergencyContactDetail.firstName'},
     {name: "emergencytitle", type: "string", mapping:'emergencyContactDetail.salutation.description'},
     {name: "emergencyGender", type: "string", mapping:'emergencyContactDetail.gender.description'},
     {name: "emergencytitleCode", type: "string", mapping:'emergencyContactDetail.salutation.code'},
     {name: "emergencyGenderCode", type: "string", mapping:'emergencyContactDetail.gender.code'},
     {name: "emergencyMiddlename", type: "string", mapping:'emergencyContactDetail.middleName'},
     {name: "emergencyLastname", type: "string", mapping:'emergencyContactDetail.lastName'},
     {name: "emergencyHousename", type: "string", mapping:'emergencyContactDetail.houseNumber'},
     {name: "emergencyPalcestreet", type: "string", mapping:'emergencyContactDetail.street'},
     {name: "emergencyCityDistrict", type: "string", mapping:'emergencyContactDetail.city'},
     {name: "emergencyPincode", type: "string", mapping:'emergencyContactDetail.pincode'},
     {name: "emergencyPhonenumber", type: "string", mapping:'emergencyContactDetail.phoneNumber'},
     {name: "emergencyMobilenumber", type: "string", mapping:'emergencyContactDetail.mobileNumber'},
     {name: "emergencyFaxnumber", type: "string", mapping:'emergencyContactDetail.faxNumber'},
     {name: "emergencyEmailaddress", type: "string", mapping:'emergencyContactDetail.email'},
     {name: "emergencyDurationofstay", type: "string", mapping:'emergencyContactDetail.stayDuration'},
     {name: "emergencyCountry", type: "string", mapping:'emergencyContactDetail.country.description'},
     {name: "emergencyState", type: "string", mapping:'emergencyContactDetail.state.description'},
     {name: "emergencyCountryCode", type: "string", mapping:'emergencyContactDetail.country.code'},
     {name: "emergencyStateCode", type: "string", mapping:'emergencyContactDetail.state.code'},
     {name: "emergencycontactType", type: "string", mapping:'emergencyContactDetail.contactType.code'},
     {name: "emergencyRelation", type: "string", mapping:'emergencyContactDetail.relationCode.code'},
     {name: "emergencyRelationCode", type: "string", mapping:'emergencyContactDetail.relationCode.description'},
     
     {name: "parmanentcontactId", type: "int", mapping:'permanentContactDetail.contactDetailsCode'},
     {name: "parmanentHousename", type: "string", mapping:'permanentContactDetail.houseNumber'},
     {name: "parmanentPlacestreet", type: "string", mapping:'permanentContactDetail.street'},
     {name: "parmanentCitydistrict", type: "string", mapping:'permanentContactDetail.city'},
     {name: "parmanentpincode", type: "string", mapping:'permanentContactDetail.pincode'},
     {name: "parmanentPhonenumber", type: "string", mapping:'permanentContactDetail.phoneNumber'},
     {name: "parmanentMobilenumber", type: "string", mapping:'permanentContactDetail.mobileNumber'},
     {name: "parmanentFaxnumber", type: "string", mapping:'permanentContactDetail.faxNumber'},
     {name: "parmanentEmailaddress", type: "string", mapping:'permanentContactDetail.email'},
     {name: "parmanentDurationofstay", type: "string", mapping:'permanentContactDetail.stayDuration'},
     {name: "parmanentCountry", type: "string", mapping:'permanentContactDetail.country.description'},
     {name: "parmanentState", type: "string", mapping:'permanentContactDetail.state.description'},
     {name: "parmanentCountryCode", type: "string", mapping:'permanentContactDetail.country.code'},
     {name: "parmanentStateCode", type: "string", mapping:'permanentContactDetail.state.code'},
     {name: "parmanentcontactType", type: "string", mapping:'permanentContactDetail.contactType.code'},
     {name : "imagePopertyBM" , mapping:"doctorDetail.imagePopertyBM" }
  ]);
  
   return doctorDetailsRecordType;
}